import scikitplot as skplt
import matplotlib.pyplot as plt

y_true = 0.8 # ground truth labels
y_probas = 0.5 # predicted probabilities generated by sklearn classifier
skplt.metrics.plot_roc(y_true, y_probas)
plt.show()